### ISSUE TITLE
The 'networkInterface' setting isn't clearly documented

### ISSUE THREAD

**Issue by seumasdunlop** [MusicDin/kubitect#28]
In `terraform/modules/base/main.tf` it reads from `var.config.cluster.nodeTemplate.networkInterface` but in `docs/examples/full-example.md` it is located at `cluster.nodeTemplate.os.networkInterface` and there is no mention of it in `docs/user-guide/configuration/cluster-node-template.md`.

I needed to use this before the static IP netplan config file was changed but the defaults are fine now.

**Comment by MusicDin** [comment]
The `networkInterface` option has been moved from `nodeTemplate` to the `nodeTemplate.os` section because it is tightly coupled with the OS image. The main purpose of the network interface option is to allow user to change the default one (`ens3`) if some custom images are used.

Thank you very much for reporting this inconsistency.
