### ISSUE TITLE
Now in AUR

### ISSUE THREAD

**Issue by Nassiel** [MusicDin/kubitect#62]
Hi, not an Issue rather than a notification, I added your package to the AUR database the developers and DevOps can now do `yay -Su kubitect` to install it with the dependencies. :)

Thank you!

**Comment by MusicDin** [comment]
Hi, thank you for your contribution to this project.

First of all, I would be interested in including this as part of the release cycle.
For example, when a new version is released, a new package should be deployed on AUR.

Since I am not an owner of the repository, how could we ensure the file integrity of the deployed packages to prevent the package from being modified later?

**Comment by Nassiel** [comment]
Let's see how we can do a post step in the workflow to execute the process automatically :)

**Comment by MusicDin** [comment]
The AUR package does not contain the latest kubitect version, and since there has been no update for 1 month, I'm closing this issue.

**Comment by Nassiel** [comment]
Updated to v2.3.0. Automating to AUR it's not an easy task. I did some research, and the best option is to call a webhook in one of my repos to upload there or do it yourself. I can give you the two files required. Let me know what's best.
